const data = {
  models: [
    {
      _id: 1,
      name: "hana jirickova",
      sex: "woman",
      image: "images/hanajirickova.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 2,
      name: "cato van ee",
      sex: "woman",
      image: "images/catovanee.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 3,
      name: "freja beha",
      sex: "woman",
      image: "images/frejabeha.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 4,
      name: "taylor hill",
      sex: "woman",
      image: "images/taylorhill.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 5,
      name: "camille rowe",
      sex: "woman",
      image: "images/camillerowe.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 6,
      name: "hana jirickova",
      sex: "woman",
      image: "images/hanajirickova.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 7,
      name: "cato van ee",
      sex: "woman",
      image: "images/catovanee.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 8,
      name: "freja beha",
      sex: "woman",
      image: "images/frejabeha.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 9,
      name: "taylor hill",
      sex: "woman",
      image: "images/taylorhill.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
    {
      _id: 10,
      name: "camille rowe",
      sex: "woman",
      image: "images/camillerowe.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
      description:
        "HAVING EARNED HER STRIPES IN THE FASHION WORLD OVER THE LAST DECADE, CATO STAYED AS DOWN TO EARTH AS ONE COULD POSSIBLY BE. HER CAREER OFFICIALLY LAUNCHED WHEN SHE WALKED PRADA AND IT DID NOT SLOW DOWN EVER SINCE. AS OF 2019 SHE IS THE NEW AMBASSADOR FOR DANCE4LIFE.",
    },
  ],
  aboutSection: [
    {
      _id: aboutSection,
      title: "about",
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At porro cum consequatur explicabo, natus facere dignissimos voluptatibus quis distinctio pariatur consectetur illo, officiis corrupti aliquid quos necessitatibus doloremque nesciunt iste?",
    },
  ],
};

export default data;
