const data = {
  models: [
    {
      _id: 1,
      name: "hana jirickova",
      sex: "woman",
      image: "images/hanajirickova.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
    },
    {
      _id: 2,
      name: "cato van ee",
      sex: "woman",
      image: "images/catovanee.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
    },
    {
      _id: 3,
      name: "freja beha",
      sex: "woman",
      image: "images/frejabeha.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
    },
    {
      _id: 4,
      name: "taylor hill",
      sex: "woman",
      image: "images/taylorhill.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
    },
    {
      _id: 5,
      name: "camille rowe",
      sex: "woman",
      image: "images/camillerowe.jpeg",
      age: 30,
      height: 178,
      bust: 84,
      waist: 58,
      hips: 87,
      hair: "blond",
      eyes: "blue green",
      shoes: 39.5,
    },
  ],
};

export default data;
